#include "apple_input_device.h"
#include "j313_apple_input.generated.h"
#if AI_ENABLE_TRACKPAD_CAPTURE
#include <wdmsec.h>
#endif

static const LONGLONG AiExpectedBases[3] = {
    J313_APPLE_INPUT_SPI_BASE,
    J313_APPLE_INPUT_AP_GPIO_BASE,
    J313_APPLE_INPUT_NUB_GPIO_BASE,
};

static const ULONG AiExpectedSizes[3] = {
    (ULONG)J313_APPLE_INPUT_SPI_SIZE,
    (ULONG)J313_APPLE_INPUT_AP_GPIO_SIZE,
    (ULONG)J313_APPLE_INPUT_NUB_GPIO_SIZE,
};

static BOOLEAN AiReadTransportOnlyParameter(WDFDRIVER Driver)
{
    UNICODE_STRING value_name;
    WDFKEY parameters_key;
    ULONG value = 1;
    NTSTATUS status;

    status = WdfDriverOpenParametersRegistryKey(
        Driver, KEY_READ, WDF_NO_OBJECT_ATTRIBUTES, &parameters_key);
    if (!NT_SUCCESS(status))
        return TRUE;
    RtlInitUnicodeString(&value_name, L"TransportOnly");
    status = WdfRegistryQueryULong(parameters_key, &value_name, &value);
    WdfRegistryClose(parameters_key);
    if (!NT_SUCCESS(status))
        return TRUE;
    return value == 0 ? FALSE : TRUE;
}

NTSTATUS AppleInputCreateDevice(WDFDRIVER Driver, PWDFDEVICE_INIT DeviceInit)
{
    WDF_PNPPOWER_EVENT_CALLBACKS callbacks;
    WDF_INTERRUPT_CONFIG interrupt_config;
    WDF_OBJECT_ATTRIBUTES lock_attributes;
    WDF_OBJECT_ATTRIBUTES timer_attributes;
    WDF_TIMER_CONFIG timer_config;
    WDF_OBJECT_ATTRIBUTES attributes;
    WDFDEVICE device;
    PAI_DEVICE_CONTEXT context;
    NTSTATUS status;

    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&callbacks);
    callbacks.EvtDevicePrepareHardware = AppleInputEvtDevicePrepareHardware;
    callbacks.EvtDeviceReleaseHardware = AppleInputEvtDeviceReleaseHardware;
    callbacks.EvtDeviceD0Entry = AppleInputEvtDeviceD0Entry;
    callbacks.EvtDeviceD0EntryPostInterruptsEnabled =
        AppleInputEvtDeviceD0EntryPostInterruptsEnabled;
    callbacks.EvtDeviceD0ExitPreInterruptsDisabled =
        AppleInputEvtDeviceD0ExitPreInterruptsDisabled;
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &callbacks);

#if AI_ENABLE_TRACKPAD_CAPTURE
    WdfDeviceInitSetCharacteristics(
        DeviceInit, FILE_AUTOGENERATED_DEVICE_NAME, TRUE);
    status = WdfDeviceInitAssignSDDLString(
        DeviceInit, &SDDL_DEVOBJ_SYS_ALL_ADM_ALL);
    if (!NT_SUCCESS(status))
        return status;
#endif

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&attributes, AI_DEVICE_CONTEXT);
    status = WdfDeviceCreate(&DeviceInit, &attributes, &device);
    if (!NT_SUCCESS(status))
        return status;

    context = AiGetDeviceContext(device);
    context->TransportOnly = TRUE;
    context->Device = device;
    context->KeyboardVhfState = AiVhfAbsent;
    context->TrackpadVhfState = AiVhfAbsent;
    context->Diagnostics.Version = AI_DIAGNOSTIC_SNAPSHOT_VERSION_3;
    context->Diagnostics.Size = sizeof(context->Diagnostics);

    WDF_OBJECT_ATTRIBUTES_INIT(&lock_attributes);
    lock_attributes.ParentObject = device;
    status = WdfWaitLockCreate(&lock_attributes, &context->TransportLock);
    if (!NT_SUCCESS(status))
        return status;
    status = WdfWaitLockCreate(&lock_attributes, &context->FrontendLock);
    if (!NT_SUCCESS(status))
        return status;
#if AI_ENABLE_TRACKPAD_CAPTURE
    status = WdfWaitLockCreate(&lock_attributes, &context->CaptureLock);
    if (!NT_SUCCESS(status))
        return status;
#endif
    context->TransportOnly = AiReadTransportOnlyParameter(Driver);

    WDF_TIMER_CONFIG_INIT(&timer_config, AiTrackpadInitTimer);
    timer_config.AutomaticSerialization = FALSE;
    WDF_OBJECT_ATTRIBUTES_INIT(&timer_attributes);
    timer_attributes.ParentObject = device;
    timer_attributes.ExecutionLevel = WdfExecutionLevelPassive;
    status = WdfTimerCreate(&timer_config, &timer_attributes,
                            &context->TrackpadInitTimer);
    if (!NT_SUCCESS(status))
        return status;

    WDF_INTERRUPT_CONFIG_INIT(&interrupt_config, AiInputInterruptIsr, NULL);
    interrupt_config.EvtInterruptWorkItem = AiTransportWorker;
    interrupt_config.PassiveHandling = TRUE;
    interrupt_config.AutomaticSerialization = FALSE;
    status = WdfInterruptCreate(device, &interrupt_config,
                                WDF_NO_OBJECT_ATTRIBUTES,
                                &context->Interrupt);
    if (!NT_SUCCESS(status))
        return status;
    status = AiDiagnosticsInitialize(device, context);
#if AI_ENABLE_TRACKPAD_CAPTURE
    if (NT_SUCCESS(status))
        status = AiTrackpadCaptureInitialize(device, context);
#endif
    return status;
}

NTSTATUS AiDeviceParseResources(WDFCMRESLIST Raw, WDFCMRESLIST Translated,
                                PAI_DEVICE_CONTEXT Context)
{
    ULONG memory = 0;
    ULONG interrupts = 0;
    ULONG raw_count = WdfCmResourceListGetCount(Raw);
    ULONG translated_count = WdfCmResourceListGetCount(Translated);

    RtlZeroMemory(Context->MemoryBase, sizeof(Context->MemoryBase));
    RtlZeroMemory(Context->MemoryLength, sizeof(Context->MemoryLength));
    Context->InterruptVector = 0;
    Context->ResourcesValidated = FALSE;
    if (raw_count != translated_count)
        return STATUS_DEVICE_CONFIGURATION_ERROR;

    for (ULONG index = 0; index < translated_count; index++) {
        PCM_PARTIAL_RESOURCE_DESCRIPTOR raw_resource =
            WdfCmResourceListGetDescriptor(Raw, index);
        PCM_PARTIAL_RESOURCE_DESCRIPTOR translated_resource =
            WdfCmResourceListGetDescriptor(Translated, index);
        if (raw_resource == NULL || translated_resource == NULL ||
            raw_resource->Type != translated_resource->Type)
            return STATUS_DEVICE_CONFIGURATION_ERROR;
        if (translated_resource->Type == CmResourceTypeMemory) {
            if (memory >= (ULONG)RTL_NUMBER_OF(AiExpectedBases) ||
                raw_resource->u.Memory.Start.QuadPart != AiExpectedBases[memory] ||
                raw_resource->u.Memory.Length != AiExpectedSizes[memory] ||
                translated_resource->u.Memory.Length != AiExpectedSizes[memory])
                return STATUS_DEVICE_CONFIGURATION_ERROR;
            Context->MemoryBase[memory] = translated_resource->u.Memory.Start;
            Context->MemoryLength[memory++] = translated_resource->u.Memory.Length;
        } else if (translated_resource->Type == CmResourceTypeInterrupt) {
            if (interrupts++ != 0 ||
                raw_resource->u.Interrupt.Vector !=
                    (ULONG)J313_APPLE_INPUT_GUEST_VINTID)
                return STATUS_DEVICE_CONFIGURATION_ERROR;
            Context->InterruptVector = translated_resource->u.Interrupt.Vector;
        }
    }
    if (memory != 3 || interrupts != 1)
        return STATUS_DEVICE_CONFIGURATION_ERROR;
    Context->ResourcesValidated = TRUE;
    return STATUS_SUCCESS;
}

NTSTATUS AppleInputEvtDevicePrepareHardware(WDFDEVICE Device, WDFCMRESLIST Raw,
                                             WDFCMRESLIST Translated)
{
    PAI_DEVICE_CONTEXT context = AiGetDeviceContext(Device);
    NTSTATUS status = AiDeviceParseResources(Raw, Translated, context);
    if (!NT_SUCCESS(status))
        return status;

    context->SpiRegisters = MmMapIoSpaceEx(context->MemoryBase[0],
        context->MemoryLength[0], PAGE_READWRITE | PAGE_NOCACHE);
    context->ApGpioRegisters = MmMapIoSpaceEx(context->MemoryBase[1],
        context->MemoryLength[1], PAGE_READWRITE | PAGE_NOCACHE);
    context->NubGpioRegisters = MmMapIoSpaceEx(context->MemoryBase[2],
        context->MemoryLength[2], PAGE_READWRITE | PAGE_NOCACHE);
    if (!context->SpiRegisters || !context->ApGpioRegisters || !context->NubGpioRegisters) {
        AppleInputEvtDeviceReleaseHardware(Device, Translated);
        return STATUS_INSUFFICIENT_RESOURCES;
    }

    status = AiSpiValidateReadOnly(context);
    if (NT_SUCCESS(status))
        status = AiGpioValidateReadOnly(context);
    if (!NT_SUCCESS(status))
        AppleInputEvtDeviceReleaseHardware(Device, Translated);
    return status;
}

NTSTATUS AppleInputEvtDeviceReleaseHardware(WDFDEVICE Device,
                                             WDFCMRESLIST Translated)
{
    UNREFERENCED_PARAMETER(Translated);
    PAI_DEVICE_CONTEXT context = AiGetDeviceContext(Device);
    AiTransportStop(context);
    if (context->NubGpioRegisters)
        MmUnmapIoSpace(context->NubGpioRegisters, context->MemoryLength[2]);
    if (context->ApGpioRegisters)
        MmUnmapIoSpace(context->ApGpioRegisters, context->MemoryLength[1]);
    if (context->SpiRegisters)
        MmUnmapIoSpace(context->SpiRegisters, context->MemoryLength[0]);
    context->SpiRegisters = NULL;
    context->ApGpioRegisters = NULL;
    context->NubGpioRegisters = NULL;
    context->ResourcesValidated = FALSE;
    return STATUS_SUCCESS;
}

NTSTATUS AppleInputEvtDeviceD0Entry(WDFDEVICE Device,
                                    WDF_POWER_DEVICE_STATE PreviousState)
{
    UNREFERENCED_PARAMETER(PreviousState);
    PAI_DEVICE_CONTEXT context = AiGetDeviceContext(Device);
    if (!context->ResourcesValidated)
        return STATUS_DEVICE_NOT_READY;
    return STATUS_SUCCESS;
}

NTSTATUS AppleInputEvtDeviceD0EntryPostInterruptsEnabled(
    WDFDEVICE Device, WDF_POWER_DEVICE_STATE PreviousState)
{
    UNREFERENCED_PARAMETER(PreviousState);
    return AiTransportStart(AiGetDeviceContext(Device));
}

NTSTATUS AppleInputEvtDeviceD0ExitPreInterruptsDisabled(
    WDFDEVICE Device, WDF_POWER_DEVICE_STATE TargetState)
{
    UNREFERENCED_PARAMETER(TargetState);
    AiTransportStop(AiGetDeviceContext(Device));
    return STATUS_SUCCESS;
}
