#ifndef APPLE_AGX_RUNTIME_HANDOFF_H
#define APPLE_AGX_RUNTIME_HANDOFF_H

#define APPLE_AGX_RUNTIME_HANDOFF_MAGIC 0x48584741u
#define APPLE_AGX_RUNTIME_HANDOFF_VERSION 1u
#define APPLE_AGX_RUNTIME_HANDOFF_READY 1u
#define APPLE_AGX_RUNTIME_HANDOFF_RELEASED 2u

typedef unsigned int APPLE_AGX_RUNTIME_HANDOFF_U32;
typedef unsigned long long APPLE_AGX_RUNTIME_HANDOFF_U64;

typedef struct _APPLE_AGX_RUNTIME_HANDOFF {
  APPLE_AGX_RUNTIME_HANDOFF_U32 Magic;
  APPLE_AGX_RUNTIME_HANDOFF_U32 Version;
  APPLE_AGX_RUNTIME_HANDOFF_U32 Size;
  APPLE_AGX_RUNTIME_HANDOFF_U32 State;
  APPLE_AGX_RUNTIME_HANDOFF_U64 Generation;
  APPLE_AGX_RUNTIME_HANDOFF_U64 HandoffPhysicalBase;
  APPLE_AGX_RUNTIME_HANDOFF_U32 HandoffBytes;
  APPLE_AGX_RUNTIME_HANDOFF_U32 Reserved;
  APPLE_AGX_RUNTIME_HANDOFF_U64 Ttbr0;
  APPLE_AGX_RUNTIME_HANDOFF_U64 Ttbr1;
} APPLE_AGX_RUNTIME_HANDOFF;

unsigned char AppleAgxRuntimeHandoffValidate(
    const APPLE_AGX_RUNTIME_HANDOFF *Handoff,
    APPLE_AGX_RUNTIME_HANDOFF_U64 ExpectedHandoffBase,
    APPLE_AGX_RUNTIME_HANDOFF_U32 ExpectedHandoffBytes);

#endif
