#ifndef APPLE_AGX_SCANOUT_H
#define APPLE_AGX_SCANOUT_H

/* ABI v1 mirrors m1n1 src/hv_agx_scanout_broker.h at MMIO +0x400. */
typedef unsigned char APPLE_AGX_SCANOUT_BOOL;
typedef unsigned int APPLE_AGX_SCANOUT_U32;
typedef unsigned long long APPLE_AGX_SCANOUT_U64;

#define APPLE_AGX_SCANOUT_FALSE ((APPLE_AGX_SCANOUT_BOOL)0u)
#define APPLE_AGX_SCANOUT_TRUE ((APPLE_AGX_SCANOUT_BOOL)1u)

#define APPLE_AGX_SCANOUT_MMIO_OFFSET 0x400u
#define APPLE_AGX_SCANOUT_MMIO_SIZE 0xa0u
#define APPLE_AGX_SCANOUT_MAGIC 0x53584741u
#define APPLE_AGX_SCANOUT_ABI_VERSION_V1 1u
#define APPLE_AGX_SCANOUT_ABI_VERSION_V2 2u
#define APPLE_AGX_SCANOUT_ABI_VERSION APPLE_AGX_SCANOUT_ABI_VERSION_V1

#define APPLE_AGX_SCANOUT_CAP_FIXED_J313 (1u << 0u)
#define APPLE_AGX_SCANOUT_CAP_BGRA8888 (1u << 1u)
#define APPLE_AGX_SCANOUT_CAP_REGISTERED_POOL (1u << 2u)
#define APPLE_AGX_SCANOUT_CAP_APPLIED_RECEIPT (1u << 3u)
#define APPLE_AGX_SCANOUT_CAP_REPEATED_PRESENT (1u << 4u)
#define APPLE_AGX_SCANOUT_CAP_LATCHED_RECEIPT (1u << 5u)
#define APPLE_AGX_SCANOUT_CAP_LATCHED_IRQ (1u << 6u)
#define APPLE_AGX_SCANOUT_REQUIRED_CAPABILITIES                              \
  (APPLE_AGX_SCANOUT_CAP_FIXED_J313 | APPLE_AGX_SCANOUT_CAP_BGRA8888 |       \
   APPLE_AGX_SCANOUT_CAP_REGISTERED_POOL |                                   \
   APPLE_AGX_SCANOUT_CAP_APPLIED_RECEIPT)
#define APPLE_AGX_SCANOUT_V2_PRESENT_CAPABILITIES                            \
  (APPLE_AGX_SCANOUT_REQUIRED_CAPABILITIES |                                 \
   APPLE_AGX_SCANOUT_CAP_REPEATED_PRESENT |                                  \
   APPLE_AGX_SCANOUT_CAP_LATCHED_RECEIPT | APPLE_AGX_SCANOUT_CAP_LATCHED_IRQ)

#define APPLE_AGX_SCANOUT_J313_WIDTH 2560u
#define APPLE_AGX_SCANOUT_J313_HEIGHT 1600u
#define APPLE_AGX_SCANOUT_J313_STRIDE 10240u
#define APPLE_AGX_SCANOUT_J313_SURFACE_SIZE 0xfa0000ULL
#define APPLE_AGX_SCANOUT_J313_POOL_SIZE 0x3800000ULL
#define APPLE_AGX_SCANOUT_ALIGNMENT 0x10000ULL
#define APPLE_AGX_SCANOUT_FORMAT_BGRA8888 1u
#define APPLE_AGX_SCANOUT_IRQ_LATCHED (1u << 0u)
#define APPLE_AGX_SCANOUT_IRQ_ERROR (1u << 1u)
#define APPLE_AGX_SCANOUT_IRQ_MASK                                             \
  (APPLE_AGX_SCANOUT_IRQ_LATCHED | APPLE_AGX_SCANOUT_IRQ_ERROR)

typedef enum _APPLE_AGX_SCANOUT_REGISTER {
  APPLE_AGX_SCANOUT_REG_MAGIC = 0x00u,
  APPLE_AGX_SCANOUT_REG_ABI_VERSION = 0x04u,
  APPLE_AGX_SCANOUT_REG_CAPABILITIES = 0x08u,
  APPLE_AGX_SCANOUT_REG_STATE = 0x0cu,
  APPLE_AGX_SCANOUT_REG_RESULT = 0x10u,
  APPLE_AGX_SCANOUT_REG_IRQ_STATUS = 0x14u,
  APPLE_AGX_SCANOUT_REG_IRQ_ENABLE = 0x18u,
  APPLE_AGX_SCANOUT_REG_RECEIPT_SEQUENCE = 0x20u,
  APPLE_AGX_SCANOUT_REG_APPLIED_SEQUENCE = 0x28u,
  APPLE_AGX_SCANOUT_REG_LATCHED_SEQUENCE = 0x30u,
  APPLE_AGX_SCANOUT_REG_ACTIVE_OFFSET = 0x38u,
  APPLE_AGX_SCANOUT_REG_POOL_PA = 0x40u,
  APPLE_AGX_SCANOUT_REG_SWAP_ID = 0x48u,
  APPLE_AGX_SCANOUT_REG_ACCEPTED_REQUESTS = 0x50u,
  APPLE_AGX_SCANOUT_REG_REJECTED_REQUESTS = 0x58u,
  APPLE_AGX_SCANOUT_REG_POOL_IPA = 0x60u,
  APPLE_AGX_SCANOUT_REG_POOL_SIZE = 0x68u,
  APPLE_AGX_SCANOUT_REG_SURFACE_OFFSET = 0x70u,
  APPLE_AGX_SCANOUT_REG_SURFACE_SIZE = 0x78u,
  APPLE_AGX_SCANOUT_REG_WIDTH = 0x80u,
  APPLE_AGX_SCANOUT_REG_HEIGHT = 0x84u,
  APPLE_AGX_SCANOUT_REG_STRIDE = 0x88u,
  APPLE_AGX_SCANOUT_REG_FORMAT = 0x8cu,
  APPLE_AGX_SCANOUT_REG_REQUEST_SEQUENCE = 0x90u,
  APPLE_AGX_SCANOUT_REG_COMMAND = 0x98u,
} APPLE_AGX_SCANOUT_REGISTER;

typedef enum _APPLE_AGX_SCANOUT_COMMAND {
  APPLE_AGX_SCANOUT_CMD_QUERY = 0u,
  APPLE_AGX_SCANOUT_CMD_REGISTER_POOL = 1u,
  APPLE_AGX_SCANOUT_CMD_PRESENT = 2u,
  APPLE_AGX_SCANOUT_CMD_RELEASE = 3u,
} APPLE_AGX_SCANOUT_COMMAND;

typedef enum _APPLE_AGX_SCANOUT_STATE {
  APPLE_AGX_SCANOUT_STATE_UNREGISTERED = 0u,
  APPLE_AGX_SCANOUT_STATE_READY = 1u,
  APPLE_AGX_SCANOUT_STATE_PENDING = 2u,
  APPLE_AGX_SCANOUT_STATE_ACTIVE = 3u,
  APPLE_AGX_SCANOUT_STATE_QUIESCING = 4u,
  APPLE_AGX_SCANOUT_STATE_FAILED = 5u,
} APPLE_AGX_SCANOUT_STATE;

typedef enum _APPLE_AGX_SCANOUT_BROKER_RESULT {
  APPLE_AGX_SCANOUT_BROKER_OK = 0u,
  APPLE_AGX_SCANOUT_BROKER_INVALID_COMMAND = 1u,
  APPLE_AGX_SCANOUT_BROKER_STALE_SEQUENCE = 2u,
  APPLE_AGX_SCANOUT_BROKER_BUSY = 3u,
  APPLE_AGX_SCANOUT_BROKER_INVALID_POOL = 4u,
  APPLE_AGX_SCANOUT_BROKER_UNMAPPED = 5u,
  APPLE_AGX_SCANOUT_BROKER_NOT_RAM = 6u,
  APPLE_AGX_SCANOUT_BROKER_NONCONTIGUOUS = 7u,
  APPLE_AGX_SCANOUT_BROKER_INVALID_SURFACE = 8u,
  APPLE_AGX_SCANOUT_BROKER_MAP_FAILED = 9u,
  APPLE_AGX_SCANOUT_BROKER_PRESENT_FAILED = 10u,
  APPLE_AGX_SCANOUT_BROKER_NOT_QUIESCED = 11u,
} APPLE_AGX_SCANOUT_BROKER_RESULT;

typedef enum _APPLE_AGX_SCANOUT_RESULT {
  AppleAgxScanoutOk = 0,
  AppleAgxScanoutInvalidArgument,
  AppleAgxScanoutNotQualified,
  AppleAgxScanoutIncompatibleMagic,
  AppleAgxScanoutIncompatibleVersion,
  AppleAgxScanoutMissingCapabilities,
  AppleAgxScanoutTransportFailed,
  AppleAgxScanoutTimeout,
  AppleAgxScanoutClockRegression,
  AppleAgxScanoutPollLimit,
  AppleAgxScanoutStaleSequence,
  AppleAgxScanoutBrokerRejected,
  AppleAgxScanoutNotQuiesced,
  AppleAgxScanoutInconsistentReceipt,
  AppleAgxScanoutSequenceExhausted,
  AppleAgxScanoutBusy,
  AppleAgxScanoutNoInterrupt,
} APPLE_AGX_SCANOUT_RESULT;

typedef struct _APPLE_AGX_SCANOUT_IO {
  void *Context;
  APPLE_AGX_SCANOUT_U64 (*NowMs)(void *Context);
  APPLE_AGX_SCANOUT_BOOL (*Read32)(void *Context, APPLE_AGX_SCANOUT_U32 Offset,
                                   APPLE_AGX_SCANOUT_U32 *Value);
  APPLE_AGX_SCANOUT_BOOL (*Read64)(void *Context, APPLE_AGX_SCANOUT_U32 Offset,
                                   APPLE_AGX_SCANOUT_U64 *Value);
  APPLE_AGX_SCANOUT_BOOL (*Write32)(void *Context, APPLE_AGX_SCANOUT_U32 Offset,
                                    APPLE_AGX_SCANOUT_U32 Value);
  APPLE_AGX_SCANOUT_BOOL (*Write64)(void *Context, APPLE_AGX_SCANOUT_U32 Offset,
                                    APPLE_AGX_SCANOUT_U64 Value);
  APPLE_AGX_SCANOUT_BOOL (*Pause)(void *Context);
} APPLE_AGX_SCANOUT_IO;

typedef struct _APPLE_AGX_SCANOUT_CLIENT {
  APPLE_AGX_SCANOUT_IO Io;
  APPLE_AGX_SCANOUT_U64 NextSequence;
  APPLE_AGX_SCANOUT_U32 MaxPolls;
  APPLE_AGX_SCANOUT_U32 LastBrokerResult;
  APPLE_AGX_SCANOUT_U32 AbiVersion;
  APPLE_AGX_SCANOUT_U32 Capabilities;
  APPLE_AGX_SCANOUT_U64 PendingPresentSequence;
  APPLE_AGX_SCANOUT_BOOL Qualified;
  APPLE_AGX_SCANOUT_BOOL PresentPending;
} APPLE_AGX_SCANOUT_CLIENT;

APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutInitialize(
    APPLE_AGX_SCANOUT_CLIENT *Client, const APPLE_AGX_SCANOUT_IO *Io,
    APPLE_AGX_SCANOUT_U64 FirstSequence, APPLE_AGX_SCANOUT_U32 MaxPolls);
APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutQualify(
    APPLE_AGX_SCANOUT_CLIENT *Client);
APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutRegisterPool(
    APPLE_AGX_SCANOUT_CLIENT *Client, APPLE_AGX_SCANOUT_U64 PoolIpa,
    APPLE_AGX_SCANOUT_U64 DeadlineMs);
APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutPresentApplied(
    APPLE_AGX_SCANOUT_CLIENT *Client, APPLE_AGX_SCANOUT_U64 SurfaceOffset,
    APPLE_AGX_SCANOUT_U64 DeadlineMs, APPLE_AGX_SCANOUT_U32 *SwapId);
APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutQueuePresent(
    APPLE_AGX_SCANOUT_CLIENT *Client, APPLE_AGX_SCANOUT_U64 SurfaceOffset,
    APPLE_AGX_SCANOUT_U64 *Sequence);
APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutEnableInterrupts(
    APPLE_AGX_SCANOUT_CLIENT *Client);
APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutDisableInterrupts(
    APPLE_AGX_SCANOUT_CLIENT *Client);
APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutConsumeInterrupt(
    APPLE_AGX_SCANOUT_CLIENT *Client, APPLE_AGX_SCANOUT_U32 *IrqStatus,
    APPLE_AGX_SCANOUT_U64 *LatchedSequence);
APPLE_AGX_SCANOUT_RESULT AppleAgxScanoutRelease(
    APPLE_AGX_SCANOUT_CLIENT *Client, APPLE_AGX_SCANOUT_U64 DeadlineMs);

#endif /* APPLE_AGX_SCANOUT_H */
