#ifndef APPLE_AGX_EVENT_ALLOCATOR_H
#define APPLE_AGX_EVENT_ALLOCATOR_H

#include "apple_agx_state.h"

#define APPLE_AGX_EVENT_COUNT 128u
#define APPLE_AGX_EVENT_WORD_COUNT (APPLE_AGX_EVENT_COUNT / 32u)

typedef struct _APPLE_AGX_EVENT_PAIR {
  APPLE_AGX_U32 Ta;
  APPLE_AGX_U32 D3;
  APPLE_AGX_U32 Lease;
} APPLE_AGX_EVENT_PAIR;

typedef struct _APPLE_AGX_EVENT_ALLOCATOR {
  APPLE_AGX_U32 Reserved[APPLE_AGX_EVENT_WORD_COUNT];
  APPLE_AGX_U32 Leases[APPLE_AGX_EVENT_COUNT];
  APPLE_AGX_U32 NextLease;
  APPLE_AGX_BOOL Initialized;
} APPLE_AGX_EVENT_ALLOCATOR;

APPLE_AGX_BOOL AppleAgxEventAllocatorInitialize(
    APPLE_AGX_EVENT_ALLOCATOR *Allocator);
APPLE_AGX_BOOL AppleAgxEventAllocatorReservePair(
    APPLE_AGX_EVENT_ALLOCATOR *Allocator, APPLE_AGX_EVENT_PAIR *Pair);
APPLE_AGX_BOOL AppleAgxEventAllocatorReleasePair(
    APPLE_AGX_EVENT_ALLOCATOR *Allocator, const APPLE_AGX_EVENT_PAIR *Pair);

#endif /* APPLE_AGX_EVENT_ALLOCATOR_H */
