#ifndef APPLE_AGX_EXP208_FRAMEBUFFER_H
#define APPLE_AGX_EXP208_FRAMEBUFFER_H

#include "apple_agx_render_template.h"

#define APPLE_AGX_EXP208_FRAMEBUFFER_WIDTH 2560u
#define APPLE_AGX_EXP208_FRAMEBUFFER_HEIGHT 1600u
#define APPLE_AGX_EXP208_FRAMEBUFFER_PITCH 10240u
#define APPLE_AGX_EXP208_FRAMEBUFFER_BYTES 0xfa0000u
#define APPLE_AGX_EXP208_FRAMEBUFFER_BACKEND_BYTES 0x800000u

typedef struct _APPLE_AGX_EXP208_FRAMEBUFFER_BINDING {
  APPLE_AGX_EXP208_RELOCATION_OBJECT OriginalTpc;
  APPLE_AGX_EXP208_RELOCATION_OBJECT OriginalTilemap;
  APPLE_AGX_EXP208_RELOCATION_OBJECT OriginalClusterTilemap;
  APPLE_AGX_U64 ArenaGpuAddress;
  APPLE_AGX_U64 ArenaPhysicalAddress;
  void *ArenaCpuAddress;
  APPLE_AGX_U32 ArenaCapacity;
  APPLE_AGX_U64 OriginalPbe0;
  APPLE_AGX_U64 OriginalPbe1;
  APPLE_AGX_U64 BoundPbe0;
  APPLE_AGX_U64 BoundPbe1;
  APPLE_AGX_BOOL Active;
} APPLE_AGX_EXP208_FRAMEBUFFER_BINDING;

APPLE_AGX_BOOL AppleAgxExp208FramebufferBind(
    void *ArenaCpuAddress, APPLE_AGX_U64 ArenaGpuAddress,
    APPLE_AGX_U64 ArenaPhysicalAddress, APPLE_AGX_U32 ArenaCapacity,
    APPLE_AGX_EXP208_RELOCATION_OBJECT *Objects,
    APPLE_AGX_U32 ObjectCount,
    APPLE_AGX_EXP208_FRAMEBUFFER_BINDING *Binding);

APPLE_AGX_BOOL AppleAgxExp208FramebufferCanUnbind(
    const APPLE_AGX_EXP208_RELOCATION_OBJECT *Objects,
    APPLE_AGX_U32 ObjectCount,
    const APPLE_AGX_EXP208_FRAMEBUFFER_BINDING *Binding);

APPLE_AGX_BOOL AppleAgxExp208FramebufferUnbind(
    APPLE_AGX_EXP208_RELOCATION_OBJECT *Objects,
    APPLE_AGX_U32 ObjectCount,
    const APPLE_AGX_EXP208_FRAMEBUFFER_BINDING *Binding);

#endif /* APPLE_AGX_EXP208_FRAMEBUFFER_H */
