#pragma once

#include <guiddef.h>

#include "apple_input_ioctl.h"

#define AI_TRACKPAD_CAPTURE_VERSION 1u
#define AI_TRACKPAD_CAPTURE_MAX_REPORTS 16u
#define AI_TRACKPAD_CAPTURE_MAX_REPORT_SIZE 512u

DEFINE_GUID(GUID_DEVINTERFACE_APPLE_INPUT_TRACKPAD_CAPTURE,
            0x1abfc64d, 0x866e, 0x46a8, 0x9a, 0x0c, 0x31, 0x11, 0x6a, 0xc4, 0x75, 0xf2);

#define IOCTL_AI_TRACKPAD_CAPTURE_ARM \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x810u, METHOD_BUFFERED, \
             FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_AI_TRACKPAD_CAPTURE_READ \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x811u, METHOD_BUFFERED, \
             FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_AI_TRACKPAD_CAPTURE_CANCEL \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x812u, METHOD_BUFFERED, \
             FILE_READ_DATA | FILE_WRITE_DATA)

typedef struct _AI_TRACKPAD_CAPTURE_ARM_REQUEST {
    ULONG Version;
    ULONG ReportLimit;
    ULONG ReportSizeLimit;
} AI_TRACKPAD_CAPTURE_ARM_REQUEST, *PAI_TRACKPAD_CAPTURE_ARM_REQUEST;

typedef struct _AI_TRACKPAD_CAPTURE_RECORD {
    ULONG Length;
    UCHAR Bytes[AI_TRACKPAD_CAPTURE_MAX_REPORT_SIZE];
} AI_TRACKPAD_CAPTURE_RECORD, *PAI_TRACKPAD_CAPTURE_RECORD;

typedef struct _AI_TRACKPAD_CAPTURE_BLOB {
    ULONG Version;
    ULONG Size;
    ULONG Armed;
    ULONG Complete;
    ULONG ReportLimit;
    ULONG ReportSizeLimit;
    ULONG ReportCount;
    ULONG DroppedCount;
    UCHAR TrackpadDescriptorSha256[AI_SHA256_DIGEST_SIZE];
    AI_TRACKPAD_CAPTURE_RECORD Records[AI_TRACKPAD_CAPTURE_MAX_REPORTS];
} AI_TRACKPAD_CAPTURE_BLOB, *PAI_TRACKPAD_CAPTURE_BLOB;

