#ifndef APPLE_AGX_UMD_INTERNAL_H
#define APPLE_AGX_UMD_INTERNAL_H

#include "direct_flip_contract.h"
#include "umd_resource_lifetime.h"

#define ADMISSION_UMD_ADAPTER_MAGIC 0x50414455u /* "UDAP" */
#define ADMISSION_UMD_DEVICE_MAGIC 0x56454455u  /* "UDEV" */
#define ADMISSION_UMD_RESOURCE_MAGIC 0x53455255u /* "URES" */

typedef struct _ADMISSION_UMD_ADAPTER {
  ULONG Magic;
  D3D10DDI_HRTADAPTER RuntimeAdapter;
  UINT Interface;
  UINT Version;
  const D3DDDI_ADAPTERCALLBACKS *Callbacks;
} ADMISSION_UMD_ADAPTER;

typedef struct _ADMISSION_UMD_DEVICE {
  ULONG Magic;
  ADMISSION_UMD_ADAPTER *Adapter;
  D3D10DDI_HRTDEVICE RuntimeDevice;
  D3D10DDI_HRTCORELAYER RuntimeCoreLayer;
  const D3DDDI_DEVICECALLBACKS *KernelCallbacks;
  const D3D11DDI_CORELAYER_DEVICECALLBACKS *UserCallbacks;
  DXGI_DDI_BASE_CALLBACKS *DxgiCallbacks;
  HANDLE KernelContext;
  ADMISSION_UMD_RETIREMENT_QUEUE Retirement;
} ADMISSION_UMD_DEVICE;

typedef struct _ADMISSION_UMD_RESOURCE {
  ULONG Magic;
  D3D10DDI_HRTRESOURCE RuntimeResource;
  D3DKMT_HANDLE KernelAllocation;
  ADMISSION_UMD_DIRECT_FLIP_RESOURCE DirectFlip;
  ADMISSION_UMD_RETIREMENT *Retirement;
} ADMISSION_UMD_RESOURCE;

VOID AdmissionUmdSetError(ADMISSION_UMD_DEVICE *Device, HRESULT Error);

#endif /* APPLE_AGX_UMD_INTERNAL_H */
