#!/usr/bin/env python3
"""Generate the synthetic-only J313 Full Graphics ABI admission contract."""

import argparse
from dataclasses import dataclass
import hashlib
import json
from pathlib import Path

try:
    from tools.generate_j313_agx_g2_contract import (
        G2ContractError,
        load_g2_contract,
    )
except ModuleNotFoundError:
    from generate_j313_agx_g2_contract import G2ContractError, load_g2_contract


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "config" / "j313-agx-abi-admission.json"
G2_PATH = ROOT / "config" / "j313-agx-g2.json"
WINDOWS_HEADER = (
    ROOT
    / "drivers"
    / "apple-agx"
    / "render-admission"
    / "include"
    / "j313_agx_abi_admission.generated.h"
)
M1N1_HEADER = ROOT / "m1n1_windows" / "src" / "hv_agx_abi_admission.generated.h"
ASL_INCLUDE = (
    ROOT
    / "mu"
    / "Platform"
    / "MacBookAirMid2020Pkg"
    / "AcpiTables"
    / "J313AppleAgxAbiAdmission.asl.inc"
)
OUTPUTS = {
    WINDOWS_HEADER: "windows",
    M1N1_HEADER: "m1n1",
    ASL_INCLUDE: "asl",
}

TOP_KEYS = {
    "contract_version",
    "platform",
    "acpi_hid",
    "source_g2_sha256",
    "synthetic_scanout_interrupt",
}
INTERRUPT_KEYS = {"guest", "trigger", "polarity", "sharing"}
EXACT_SYNTHETIC_GUEST_INTID = 889
RESERVED_GUEST_INTIDS = {64, 865}


class AdmissionContractError(ValueError):
    """The candidate-only admission contract is malformed."""


@dataclass(frozen=True)
class AdmissionContract:
    contract_version: int
    platform: str
    acpi_hid: str
    source_g2_sha256: str
    memory_resources: tuple[tuple[str, int, int], ...]
    physical_guest_interrupts: tuple[int, ...]
    synthetic_scanout_guest_interrupt: int


def _exact(value, keys, where):
    if not isinstance(value, dict) or set(value) != set(keys):
        raise AdmissionContractError(
            f"{where} keys must be exactly {sorted(keys)}"
        )


def load_admission_contract(contract_path=CONTRACT_PATH, g2_path=G2_PATH):
    contract_path = Path(contract_path)
    g2_path = Path(g2_path)
    try:
        data = json.loads(contract_path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise AdmissionContractError(str(exc)) from exc
    _exact(data, TOP_KEYS, "admission contract")
    if data["contract_version"] != 1:
        raise AdmissionContractError("contract_version must be 1")
    if data["platform"] != "J313" or data["acpi_hid"] != "APPL0002":
        raise AdmissionContractError("platform/HID identity mismatch")

    expected_source = hashlib.sha256(g2_path.read_bytes()).hexdigest()
    if data["source_g2_sha256"] != expected_source:
        raise AdmissionContractError("source G2 SHA-256 mismatch")
    try:
        g2 = load_g2_contract(g2_path)
    except G2ContractError as exc:
        raise AdmissionContractError(str(exc)) from exc

    interrupt = data["synthetic_scanout_interrupt"]
    _exact(interrupt, INTERRUPT_KEYS, "synthetic_scanout_interrupt")
    if interrupt != {
        "guest": EXACT_SYNTHETIC_GUEST_INTID,
        "trigger": "edge",
        "polarity": "active_high",
        "sharing": "exclusive",
    }:
        raise AdmissionContractError("synthetic scanout interrupt mismatch")
    physical_guests = tuple(route.guest for route in g2.interrupt_routes)
    if (
        EXACT_SYNTHETIC_GUEST_INTID in physical_guests
        or EXACT_SYNTHETIC_GUEST_INTID in RESERVED_GUEST_INTIDS
    ):
        raise AdmissionContractError("synthetic scanout interrupt collides")

    memory = g2.acpi_mmio + g2.synthetic_mmio
    expected_memory = (
        ("sgx_mmio", 0x204000000, 0x4000000),
        ("gpu", 0x9FFFB8000, 0x4000),
        ("handoff", 0x9FFF70000, 0x4000),
        ("power_broker", 0x300000000, 0x1000),
    )
    if memory != expected_memory:
        raise AdmissionContractError("candidate memory geometry mismatch")
    return AdmissionContract(
        contract_version=1,
        platform="J313",
        acpi_hid="APPL0002",
        source_g2_sha256=expected_source,
        memory_resources=memory,
        physical_guest_interrupts=physical_guests,
        synthetic_scanout_guest_interrupt=EXACT_SYNTHETIC_GUEST_INTID,
    )


def _render_header(contract, prefix, guard):
    lines = [
        "/* Generated by tools/generate_j313_agx_abi_admission.py; do not edit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f'#define {prefix}_PROFILE_IDENTITY "agx-abi-admission"',
        f'#define {prefix}_SOURCE_G2_SHA256 "{contract.source_g2_sha256}"',
        f"#define {prefix}_CONTRACT_VERSION 1u",
        f"#define {prefix}_SYNTHETIC_SCANOUT_GUEST_INTID 889u",
    ]
    for name, base, size in contract.memory_resources:
        macro = name.upper()
        lines.append(f"#define {prefix}_{macro}_BASE 0x{base:x}ULL")
        lines.append(f"#define {prefix}_{macro}_SIZE 0x{size:x}ULL")
    lines.extend(["", f"#endif /* {guard} */", ""])
    return "\n".join(lines)


def render_windows_header(contract):
    return _render_header(
        contract,
        "J313_AGX_ABI_ADMISSION",
        "J313_AGX_ABI_ADMISSION_GENERATED_H",
    )


def render_m1n1_header(contract):
    return _render_header(
        contract,
        "HV_AGX_ABI_ADMISSION",
        "HV_AGX_ABI_ADMISSION_GENERATED_H",
    )


def _qword_memory(base, size):
    maximum = base + size - 1
    return f"""        QWordMemory (ResourceConsumer, PosDecode, MinFixed, MaxFixed,
            NonCacheable, ReadWrite, 0x0,
            0x{base:016X}, 0x{maximum:016X}, 0x0,
            0x{size:016X}, ,, , AddressRangeMemory, TypeStatic)"""


def render_asl_include(contract):
    memory = "\n".join(
        _qword_memory(base, size)
        for _name, base, size in contract.memory_resources
    )
    return f"""// Generated by tools/generate_j313_agx_abi_admission.py; do not edit.
Device (AGX0)
{{
    Name (_HID, "{contract.acpi_hid}")
    Name (_UID, Zero)
    Name (_CCA, One)
    Name (_STA, 0x0F)
    Name (_CRS, ResourceTemplate ()
    {{
{memory}
        Interrupt (ResourceConsumer, Edge, ActiveHigh, Exclusive)
        {{ {contract.synthetic_scanout_guest_interrupt} }}
    }})
    Name (_DSD, Package ()
    {{
        ToUUID ("daffd814-6eba-4d8c-8a91-bc9bbf4aa301"),
        Package ()
        {{
            Package () {{ "agx-profile", "abi-admission" }},
            Package () {{ "agx-abi-admission-version", 0x01 }},
            Package () {{ "agx-source-g2-sha256", "{contract.source_g2_sha256}" }}
        }}
    }})
}}
"""


def _render(kind, contract):
    return {
        "windows": render_windows_header,
        "m1n1": render_m1n1_header,
        "asl": render_asl_include,
    }[kind](contract)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = load_admission_contract()
    stale = []
    for path, kind in OUTPUTS.items():
        rendered = _render(kind, contract)
        if args.check:
            if not path.is_file() or path.read_text() != rendered:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered)
    if stale:
        raise SystemExit("stale generated outputs: " + ", ".join(stale))


if __name__ == "__main__":
    main()
