#!/usr/bin/env python3
"""Generate identical J313 Apple input constants for m1n1, Mu, and Windows."""

import argparse
from pathlib import Path
import tempfile

try:
    from tools.apple_input_contract import load_contract
except ModuleNotFoundError:
    from apple_input_contract import load_contract


ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "config" / "j313-apple-input.json"
OUTPUTS = {
    "m1n1": ROOT / "m1n1_windows" / "src" / "hv_apple_input.generated.h",
    "asl": ROOT / "mu" / "Platform" / "MacBookAirMid2020Pkg" / "AcpiTables" / "J313AppleInput.asl.inc",
    "windows": ROOT / "drivers" / "apple-input" / "windows" / "include" / "j313_apple_input.generated.h",
}


def _header(c, guard, prefix):
    values = {
        "CONTRACT_VERSION": c.contract_version,
        "SPI_BASE": c.spi.base,
        "SPI_SIZE": c.spi.size,
        "SPI_SOURCE_HZ": c.spi.source_hz,
        "SPI_BUS_HZ": c.spi.bus_hz,
        "AP_GPIO_BASE": c.ap_gpio.base,
        "AP_GPIO_SIZE": c.ap_gpio.size,
        "AP_GPIO_PIN": c.ap_gpio.pin,
        "NUB_GPIO_BASE": c.nub_gpio.base,
        "NUB_GPIO_SIZE": c.nub_gpio.size,
        "NUB_GPIO_PIN": c.nub_gpio.pin,
        "IRQ_STARTUP_GROUP": c.interrupt.startup_group,
        "PHYSICAL_PARENT_IRQ": c.interrupt.startup_parent,
        "GUEST_VINTID": c.interrupt.guest_vintid,
        "RESET_HIGH_US": c.timings_us.reset_high,
        "RESET_LOW_US": c.timings_us.reset_low,
        "BOOT_WAIT_US": c.timings_us.boot_wait,
        "CS_SETUP_US": c.timings_us.cs_setup,
        "CS_HOLD_US": c.timings_us.cs_hold,
        "CS_INACTIVE_US": c.timings_us.cs_inactive,
        "TRANSFER_TIMEOUT_US": c.timings_us.transfer_timeout,
    }
    lines = ["/* Generated by tools/generate_apple_input_contract.py; do not edit. */",
             f"#ifndef {guard}", f"#define {guard}", ""]
    for name, value in values.items():
        lines.append(f"#define {prefix}_{name} 0x{value:x}ULL")
    parents = ", ".join(f"{value}u" for value in c.interrupt.parent_candidates)
    lines.extend([f"#define {prefix}_PARENT_IRQ_COUNT {len(c.interrupt.parent_candidates)}u",
                  f"#define {prefix}_PARENT_IRQ_VALUES {{ {parents} }}", "", f"#endif /* {guard} */", ""])
    return "\n".join(lines)


def render_m1n1(c):
    return _header(c, "HV_APPLE_INPUT_GENERATED_H", "HV_APPLE_INPUT")


def render_windows(c):
    return _header(c, "J313_APPLE_INPUT_GENERATED_H", "J313_APPLE_INPUT")


def _qword_memory(base, size):
    maximum = base + size - 1
    return f"""            QWordMemory (ResourceConsumer, PosDecode, MinFixed, MaxFixed,
                NonCacheable, ReadWrite, 0x0,
                0x{base:016X}, 0x{maximum:016X}, 0x0,
                0x{size:016X}, ,, , AddressRangeMemory, TypeStatic)"""


def render_asl(c):
    return f"""// Generated by tools/generate_apple_input_contract.py; do not edit.
Device (AINP)
{{
    Name (_HID, \"{c.acpi_hid}\")
    Name (_UID, Zero)
    Name (_CCA, One)
    Name (_STA, 0x0F)
    Name (_CRS, ResourceTemplate ()
    {{
{_qword_memory(c.spi.base, c.spi.size)}
{_qword_memory(c.ap_gpio.base, c.ap_gpio.size)}
{_qword_memory(c.nub_gpio.base, c.nub_gpio.size)}
        Interrupt (ResourceConsumer, Level, ActiveLow, Shared, ,, )
        {{
            0x{c.interrupt.guest_vintid:08X}
        }}
    }})
    Name (_DSD, Package ()
    {{
        ToUUID (\"daffd814-6eba-4d8c-8a91-bc9bbf4aa301\"),
        Package ()
        {{
            Package () {{ \"contract-version\", {c.contract_version} }},
            Package () {{ \"spi-bus-hz\", {c.spi.bus_hz} }},
            Package () {{ \"ap-gpio-pin\", {c.ap_gpio.pin} }},
            Package () {{ \"nub-gpio-pin\", {c.nub_gpio.pin} }},
            Package () {{ \"physical-parent-irq\", {c.interrupt.startup_parent} }},
            Package () {{ \"reset-high-us\", {c.timings_us.reset_high} }},
            Package () {{ \"reset-low-us\", {c.timings_us.reset_low} }},
            Package () {{ \"boot-wait-us\", {c.timings_us.boot_wait} }},
            Package () {{ \"cs-setup-us\", {c.timings_us.cs_setup} }},
            Package () {{ \"cs-hold-us\", {c.timings_us.cs_hold} }},
            Package () {{ \"cs-inactive-us\", {c.timings_us.cs_inactive} }},
            Package () {{ \"transfer-timeout-us\", {c.timings_us.transfer_timeout} }}
        }}
    }})
}}
"""


def _atomic_write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", dir=path.parent, delete=False) as handle:
        handle.write(content)
        temp = Path(handle.name)
    temp.replace(path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    c = load_contract(CONTRACT)
    rendered = {"m1n1": render_m1n1(c), "asl": render_asl(c), "windows": render_windows(c)}
    stale = [name for name, path in OUTPUTS.items() if not path.exists() or path.read_text() != rendered[name]]
    if args.check:
        if stale:
            parser.error("generated Apple input contract is stale: " + ", ".join(stale))
        return
    for name in stale:
        _atomic_write(OUTPUTS[name], rendered[name])


if __name__ == "__main__":
    main()
