#ifndef ADMISSION_GPUVA_G1B_PROFILE_H
#define ADMISSION_GPUVA_G1B_PROFILE_H

#ifndef ADMISSION_GPUVA_G1B_PAGE_PROFILE
#define ADMISSION_GPUVA_G1B_PAGE_PROFILE 0
#endif
#ifndef ADMISSION_GPUVA_G1B_ALLOCATION_HINT
#define ADMISSION_GPUVA_G1B_ALLOCATION_HINT 0
#endif
#if ADMISSION_GPUVA_G1B_ALLOCATION_HINT != 0 && \
    ADMISSION_GPUVA_G1B_PAGE_PROFILE == 0
#error G1b allocation hint requires a WDDM 3.2 profile
#endif

#if ADMISSION_GPUVA_G1B_PAGE_PROFILE == 16
#define ADMISSION_G1B_SLAB_SIZE DXGK_PAGESIZE_16KB
#define ADMISSION_G1B_MINIMUM_PAGE DXGK_PAGESIZE_16KB
#define ADMISSION_G1B_RECOMMENDED_PAGE DXGK_PAGESIZE_16KB
#define ADMISSION_G1B_USE64K 0u
#elif ADMISSION_GPUVA_G1B_PAGE_PROFILE == 64
#define ADMISSION_G1B_SLAB_SIZE DXGK_PAGESIZE_64KB
#define ADMISSION_G1B_MINIMUM_PAGE DXGK_PAGESIZE_64KB
#define ADMISSION_G1B_RECOMMENDED_PAGE DXGK_PAGESIZE_64KB
#define ADMISSION_G1B_USE64K 1u
#elif ADMISSION_GPUVA_G1B_PAGE_PROFILE != 0
#error Unsupported G1b segment page profile
#endif

#if ADMISSION_GPUVA_G1B_PAGE_PROFILE != 0
#define ADMISSION_G1B_WDDM_VERSION DXGKDDI_WDDMv3_2
#define ADMISSION_G1B_INTERFACE_VERSION DXGKDDI_INTERFACE_VERSION_WDDM3_2
#else
#define ADMISSION_G1B_WDDM_VERSION DXGKDDI_WDDMv3_0
#define ADMISSION_G1B_INTERFACE_VERSION DXGKDDI_INTERFACE_VERSION_WDDM3_0
#endif

#endif
